name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:  
        output1: ${{ steps.step2.outputs.high_vulnerability_count }}
        output2: ${{ steps.step2.outputs.vulnerability_count }}
        output3: ${{ steps.step2.outputs.medium_vulnerability_count }}
    steps:
      - name: Checkout code
        id: step1
        uses: actions/checkout@v2
      - name: Scan Remote Image
        id: step2
        uses: rajeshkio/neuvector-image-scan-action@main
        with:
          image-registry: https://registry.hub.docker.com
          image-registry-username: ${{ secrets.DOCKER_USERNAME }}
          image-registry-password: ${{ secrets.DOCKER_PASSWORD }}
          image-repository: rk90229/count-user-visits
          image-tag: latest
  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "${{needs.build.outputs.output1}}, ${{needs.build.outputs.output2}}, ${{needs.build.outputs.output3}}"
